GRANT USAGE ON *.* TO 'ceilometer'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `ceilometer`.* TO 'ceilometer'@'%'
GRANT USAGE ON *.* TO 'glance'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `glance`.* TO 'glance'@'%'
GRANT USAGE ON *.* TO 'heat'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `heat`.* TO 'heat'@'%'
GRANT USAGE ON *.* TO 'ironic'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `ironic`.* TO 'ironic'@'%'
GRANT USAGE ON *.* TO 'keystone'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `keystone`.* TO 'keystone'@'%'
GRANT USAGE ON *.* TO 'neutron'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `neutron`.* TO 'neutron'@'%'
GRANT USAGE ON *.* TO 'nova'@'%' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `nova`.* TO 'nova'@'%'
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION
GRANT USAGE ON *.* TO 'ceilometer'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `ceilometer`.* TO 'ceilometer'@'192.0.2.1'
GRANT USAGE ON *.* TO 'glance'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `glance`.* TO 'glance'@'192.0.2.1'
GRANT USAGE ON *.* TO 'heat'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `heat`.* TO 'heat'@'192.0.2.1'
GRANT USAGE ON *.* TO 'ironic'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `ironic`.* TO 'ironic'@'192.0.2.1'
GRANT USAGE ON *.* TO 'keystone'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `keystone`.* TO 'keystone'@'192.0.2.1'
GRANT USAGE ON *.* TO 'neutron'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `neutron`.* TO 'neutron'@'192.0.2.1'
GRANT USAGE ON *.* TO 'nova'@'192.0.2.1' IDENTIFIED BY PASSWORD 'XXXX'
GRANT ALL PRIVILEGES ON `nova`.* TO 'nova'@'192.0.2.1'
GRANT ALL PRIVILEGES ON *.* TO 'root'@'::1' WITH GRANT OPTION
GRANT ALL PRIVILEGES ON *.* TO 'root'@'undercloud-server.redhat.com' WITH GRANT OPTION
GRANT PROXY ON ''@'' TO 'root'@'undercloud-server.redhat.com' WITH GRANT OPTION
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION
GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION
